### ISSUE TITLE
下载图片功能无效

### ISSUE THREAD

**Issue by ckaqq** [qious/gallery-client#1]
![image](https://user-images.githubusercontent.com/11495438/61366589-6eef3800-a8bc-11e9-8eac-ca23e394ada6.png)
就是图片里的那个按钮，点了之后在新窗口打开了，没有下载，大佬有啥解决方案没？

**Comment by qiujun8023** [comment]
暂时没找到相关的解决方案

https://github.com/dimsemenov/PhotoSwipe/issues/1218

**Comment by ckaqq** [comment]
用边缘规则解决了，不过需要关闭 WebP自适应 功能，否则下载的图片有可能打不开
![image](https://user-images.githubusercontent.com/11495438/61601117-9cdece80-ac66-11e9-9936-23439a2b6d4d.png)
![image](https://user-images.githubusercontent.com/11495438/61601152-c26bd800-ac66-11e9-936a-c9a1a9137111.png)
